### ISSUE TITLE
Refactor `Augustash\Facebookpixel\Block\Revenue` to extend `Snippet`

### ISSUE THREAD

**Issue by grafikchaos** [augustash/magento2-module-facebookpixel#6]
### Suggestions for refactoring:

+ Remove the following lines:
  - `use Augustash\Facebookpixel\Block\Snippet as SnippetHelper;` [Line 6](https://github.com/augustash/magento2-module-facebookpixel/blob/313bb757537dbadd9de03d310a77ef41c3c32349/Block/Revenue.php#L6)
  - `SnippetHelper $snippet,` [Line 26](https://github.com/augustash/magento2-module-facebookpixel/blob/313bb757537dbadd9de03d310a77ef41c3c32349/Block/Revenue.php#L26)
+ Change `class Revenue extends \Magento\Framework\View\Element\Template` to `class Revenue extends Snippet` ([Line 11](https://github.com/augustash/magento2-module-facebookpixel/blob/313bb757537dbadd9de03d310a77ef41c3c32349/Block/Revenue.php#L11))
+ Change `revenue.phtml` use of `<?php if ($this->snippet->getIsEnabled() && $this->getTrackRevenue()): ?>` to `<?php if ($this->getIsEnabled() && $this->getTrackRevenue()): ?>` ([Line 4](https://github.com/augustash/magento2-module-facebookpixel/blob/313bb757537dbadd9de03d310a77ef41c3c32349/view/frontend/templates/revenue.phtml#L4))

**Comment by kazajhodo** [comment]
The refactor idea was solid, I approached it slightly differently.

I added in a helper class, which allows access to:
- Check if the module is enabled
- Check if advanced revenue tracking is enabled
- Retrieve the Facebookpixel account number

Then I removed snippet entirely and combined the snippet.php and revenue.php block classes into one class called Blocks within Blocks.php. This contains wrapper methods to access needed values from the new helper.

Both blocks now reference the new class. The templates of course remain separate.

The same function names were used in the helper wrappers within Blocks.php, so that backward compatibility remains intact.

Block templates were updated. All checks are now $this->method().
